---
- name: Prepare all Kubernetes nodes
  hosts: k8s_nodes
  become: true
  roles:
    - k8s-common

- name: Initialize Kubernetes master
  hosts: k8s_master
  become: true
  roles:
    - k8s-master

- name: Join workers to cluster
  hosts: k8s_workers
  become: true
  roles:
    - k8s-worker
